== Um Mergulho no JavaScript

=== Pensando como um Programador

=== Exemplo - Jogo adivinhe um número

Vamos imaginar que o seu chefe te deu as seguintes diretrizes para criar este jogo:

    Quero que você crie um jogo simples do tipo adivinhe um número. Ele deve gerar um número aleatório de 1 a 100, depois desafiar o jogador a adivinhar o número em 10 rodadas. A cada rodada deve ser dito ao jogador se ele está certo ou errado, se estiver errado, deve ser dito se o palpite é muito baixo ou muito alto. Também deve ser mostrado ao jogador os números que ele tentou adivinhar anteriormente. O jogo termina se o jogador acertar o número ou acabarem o número de tentativas. Quando o jogo acabar, deve ser dado ao jogador a opção de jogar novamente.

Olhando para o enunciado, a primeira coisa que devemos fazer é quebrá-lo em pequenas tarefas, da forma mais parecida com o pensamento de um programador quanto possível:

    1. Gerar um número aleatório entre 1 e 100.
    2. Gravar o número do turno que o jogador está. Iniciar em 1.
    3. Dar ao jogador uma forma de adivinhar o número.
    4. Após a tentativa ter sido submetida, primeiro gravar em algum lugar para que o usuário possa ver as tentativas anteriores.
    5. Depois, verificar se o palpite está correto.
    6. Se estiver correto:
        Escrever mensagem de parabéns.
        Impedir que o jogador insira mais respostas (isso pode bugar o jogo).
        Mostrar controle que permita ao jogador reiniciar o jogo.
    7. Se o palpite estiver errado e o jogador ainda tem turnos sobrando:
        Dizer ao jogador que ele está errado.
        Permitir que ele insira outra resposta.
        Incrementar o número do turno em 1.
    8. Se o jogador está errado mas não tem turnos sobrando:
        Dizer ao jogador que o jogo acabou.
        Impedir que o jogador insira mais respostas (isso pode bugar o jogo).
        Mostrar controle que permita ao jogador reiniciar o jogo.
    9. Quando reiniciar, tenha certeza de resetar todas as variáveis e a interface do jogo, então volte para o passo 1.

==== Configuração inicial

Baixar html de exemplo em https://github.com/mdn/learning-area/blob/main/javascript/introduction-to-js-1/first-splash/number-guessing-game-start.html

==== Adicionando variáveis para armazenas nossos dados


[source, javascript]
----
var numeroAleatorio = Math.floor(Math.random() * 100) + 1;

var palpites = document.querySelector(".palpites");
var ultimoResultado = document.querySelector(".ultimoResultado");
var baixoOuAlto = document.querySelector(".baixoOuAlto");

var envioPalpite = document.querySelector(".envioPalpite");
var campoPalpite = document.querySelector(".campoPalpite");

var contagemPalpites = 1;
var botaoReinicio;
----

==== Eventos

São ações que acontecem no navegador, como um botão sendo clicado, ou uma página carregada, ou um vídeo tocando; ações as quais podemos responder executando blocos de código.

Os contrutores que monitoram os acontecimentos de eventos são chamados *event listeners*, e os blocos de código executados em resposta ao acontecimento do evento são chamados de *event handlers*.

==== Finalizando a funcionalidade do jogo

Configurada função para fim de jogo.

==== Loops

[source, javascript]
----
for (var i = 1; i < 21; i++) {
    console.log(i);
}
----

mesmo funcionamento do for C#. Enquanto o segundo argumento (i < 21) for verdadeiro, o loop roda e realiza o terceiro argumento, neste caso incrementando.

==== Uma pequena discussão sobre objetos

Em JavaScript, tudo é um objeto.

O objeto é uma coleção de funcionalidades relacionadas armazenadas em um único agrupamento.

==== Brincando com objetos no navegador

É possível inserir valor em uma variável por meio do console do navegador.

No exemplo dado, ao digitar campoPalpite.Value = "Olá", a variável recebeu o valor olá no campo input.